# Site Settings
site_name: ChaoticCyber
site_author: Aids
site_url: https://chaoticcyber.com
docs_dir: ./docs # Obsidian Vault

# Material Configuration
theme:
  name: windmill-dark
  custom_dir: assets/ # Contains custom 'home.html' coverpage (and 'main.html')